<?php

/**
 * BaseGame
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $home_game
 * @property integer $away_game
 * @property integer $home_id
 * @property integer $away_id
 * @property timestamp $due
 * @property integer $home_score
 * @property integer $away_score
 * @property Team $Home
 * @property Team $Away
 * @property Doctrine_Collection $Pick
 * 
 * @method integer             getHomeGame()   Returns the current record's "home_game" value
 * @method integer             getAwayGame()   Returns the current record's "away_game" value
 * @method integer             getHomeId()     Returns the current record's "home_id" value
 * @method integer             getAwayId()     Returns the current record's "away_id" value
 * @method timestamp           getDue()        Returns the current record's "due" value
 * @method integer             getHomeScore()  Returns the current record's "home_score" value
 * @method integer             getAwayScore()  Returns the current record's "away_score" value
 * @method Team                getHome()       Returns the current record's "Home" value
 * @method Team                getAway()       Returns the current record's "Away" value
 * @method Doctrine_Collection getPick()       Returns the current record's "Pick" collection
 * @method Game                setHomeGame()   Sets the current record's "home_game" value
 * @method Game                setAwayGame()   Sets the current record's "away_game" value
 * @method Game                setHomeId()     Sets the current record's "home_id" value
 * @method Game                setAwayId()     Sets the current record's "away_id" value
 * @method Game                setDue()        Sets the current record's "due" value
 * @method Game                setHomeScore()  Sets the current record's "home_score" value
 * @method Game                setAwayScore()  Sets the current record's "away_score" value
 * @method Game                setHome()       Sets the current record's "Home" value
 * @method Game                setAway()       Sets the current record's "Away" value
 * @method Game                setPick()       Sets the current record's "Pick" collection
 * 
 * @package    madness]
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseGame extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('game');
        $this->hasColumn('home_game', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('away_game', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('home_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('away_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('due', 'timestamp', null, array(
             'type' => 'timestamp',
             ));
        $this->hasColumn('home_score', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('away_score', 'integer', null, array(
             'type' => 'integer',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Team as Home', array(
             'local' => 'home_id',
             'foreign' => 'id'));

        $this->hasOne('Team as Away', array(
             'local' => 'away_id',
             'foreign' => 'id'));

        $this->hasMany('Pick', array(
             'local' => 'id',
             'foreign' => 'game_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}