<?php

/**
 * BaseBracket
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $user_id
 * @property string $name
 * @property integer $score
 * @property User $User
 * @property Doctrine_Collection $Pick
 * 
 * @method integer             getUserId()  Returns the current record's "user_id" value
 * @method string              getName()    Returns the current record's "name" value
 * @method integer             getScore()   Returns the current record's "score" value
 * @method User                getUser()    Returns the current record's "User" value
 * @method Doctrine_Collection getPick()    Returns the current record's "Pick" collection
 * @method Bracket             setUserId()  Sets the current record's "user_id" value
 * @method Bracket             setName()    Sets the current record's "name" value
 * @method Bracket             setScore()   Sets the current record's "score" value
 * @method Bracket             setUser()    Sets the current record's "User" value
 * @method Bracket             setPick()    Sets the current record's "Pick" collection
 * 
 * @package    madness]
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseBracket extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('bracket');
        $this->hasColumn('user_id', 'integer', 8, array(
             'type' => 'integer',
             'length' => 8,
             ));
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));
        $this->hasColumn('score', 'integer', null, array(
             'type' => 'integer',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('User', array(
             'local' => 'user_id',
             'foreign' => 'id'));

        $this->hasMany('Pick', array(
             'local' => 'id',
             'foreign' => 'bracket_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}