<?php

/**
 * BasePick
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $bracket_id
 * @property integer $game_id
 * @property integer $team_id
 * @property Bracket $Bracket
 * @property Game $Game
 * @property Team $Team
 * 
 * @method integer getBracketId()  Returns the current record's "bracket_id" value
 * @method integer getGameId()     Returns the current record's "game_id" value
 * @method integer getTeamId()     Returns the current record's "team_id" value
 * @method Bracket getBracket()    Returns the current record's "Bracket" value
 * @method Game    getGame()       Returns the current record's "Game" value
 * @method Team    getTeam()       Returns the current record's "Team" value
 * @method Pick    setBracketId()  Sets the current record's "bracket_id" value
 * @method Pick    setGameId()     Sets the current record's "game_id" value
 * @method Pick    setTeamId()     Sets the current record's "team_id" value
 * @method Pick    setBracket()    Sets the current record's "Bracket" value
 * @method Pick    setGame()       Sets the current record's "Game" value
 * @method Pick    setTeam()       Sets the current record's "Team" value
 * 
 * @package    madness]
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BasePick extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('pick');
        $this->hasColumn('bracket_id', 'integer', 8, array(
             'type' => 'integer',
             'length' => 8,
             ));
        $this->hasColumn('game_id', 'integer', 8, array(
             'type' => 'integer',
             'length' => 8,
             ));
        $this->hasColumn('team_id', 'integer', 8, array(
             'type' => 'integer',
             'length' => 8,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Bracket', array(
             'local' => 'bracket_id',
             'foreign' => 'id'));

        $this->hasOne('Game', array(
             'local' => 'game_id',
             'foreign' => 'id'));

        $this->hasOne('Team', array(
             'local' => 'team_id',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}