<?php

/**
 * BaseTeam
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property Doctrine_Collection $Game
 * @property Doctrine_Collection $Pick
 * 
 * @method string              getName() Returns the current record's "name" value
 * @method Doctrine_Collection getGame() Returns the current record's "Game" collection
 * @method Doctrine_Collection getPick() Returns the current record's "Pick" collection
 * @method Team                setName() Sets the current record's "name" value
 * @method Team                setGame() Sets the current record's "Game" collection
 * @method Team                setPick() Sets the current record's "Pick" collection
 * 
 * @package    madness]
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseTeam extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('team');
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Game', array(
             'local' => 'id',
             'foreign' => 'home_id'));

        $this->hasMany('Pick', array(
             'local' => 'id',
             'foreign' => 'team_id'));
    }
}