<?php

/**
 * BaseUser
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property string $password
 * @property Doctrine_Collection $Bracket
 * 
 * @method string              getName()     Returns the current record's "name" value
 * @method string              getPassword() Returns the current record's "password" value
 * @method Doctrine_Collection getBracket()  Returns the current record's "Bracket" collection
 * @method User                setName()     Sets the current record's "name" value
 * @method User                setPassword() Sets the current record's "password" value
 * @method User                setBracket()  Sets the current record's "Bracket" collection
 * 
 * @package    madness]
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseUser extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('user');
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));
        $this->hasColumn('password', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Bracket', array(
             'local' => 'id',
             'foreign' => 'user_id'));
    }
}