<?php

/**
 * Game
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    madness]
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
class Game extends BaseGame
{
  
  public function getPossibleTeamIds()
  {
    $teams = array();
    
    if($this->home_id) $teams = array((int) $this->home_id);
    else $teams = Doctrine::getTable('Game')->find($this->home_game)->getPossibleTeamIds();
    //print_r($teams);
    if($this->away_id) $teams[] = (int) $this->away_id;
    else $teams = array_merge($teams, Doctrine::getTable('Game')->find($this->away_game)->getPossibleTeamIds());
    //print_r($teams);
    
    return $teams;
  }
}
